export const CATEGORIES = [
  { _id: 'cat_1', name: 'Fruits & Vegs', emoji: '🥦', color: '#e8f5e9', textColor: '#2e7d32', slug: 'fruits-vegs' },
  { _id: 'cat_2', name: 'Dairy & Eggs', emoji: '🥛', color: '#e3f2fd', textColor: '#1565c0', slug: 'dairy-eggs' },
  { _id: 'cat_3', name: 'Bakery', emoji: '🍞', color: '#fff8e1', textColor: '#e65100', slug: 'bakery' },
  { _id: 'cat_4', name: 'Beverages', emoji: '🥤', color: '#fce4ec', textColor: '#c62828', slug: 'beverages' },
  { _id: 'cat_5', name: 'Snacks', emoji: '🍿', color: '#f3e5f5', textColor: '#6a1b9a', slug: 'snacks' },
  { _id: 'cat_6', name: 'Meat & Fish', emoji: '🍗', color: '#fbe9e7', textColor: '#bf360c', slug: 'meat-fish' },
  { _id: 'cat_7', name: 'Personal Care', emoji: '🧴', color: '#e0f7fa', textColor: '#00695c', slug: 'personal-care' },
  { _id: 'cat_8', name: 'Baby Care', emoji: '👶', color: '#fff3e0', textColor: '#e65100', slug: 'baby-care' },
  { _id: 'cat_9', name: 'Breakfast', emoji: '🥞', color: '#f9fbe7', textColor: '#558b2f', slug: 'breakfast' },
  { _id: 'cat_10', name: 'Frozen Foods', emoji: '🧊', color: '#e8eaf6', textColor: '#283593', slug: 'frozen-foods' },
]

export const PRODUCTS = [
  // Fruits & Vegs
  {
    _id: 'p_1',
    name: 'Bananas',
    unit: '6 pcs (approx 500g)',
    price: 39,
    originalPrice: 49,
    discount: 20,
    category: 'cat_1',
    categoryName: 'Fruits & Vegs',
    stock: 50,
    gradient: 'from-yellow-100 to-yellow-200',
    emoji: '🍌',
    description: 'Fresh, ripe bananas. Rich in potassium and natural sugars for quick energy.',
    deliveryTime: '10 mins',
    rating: 4.5,
    reviews: 128,
  },
  {
    _id: 'p_2',
    name: 'Red Apples',
    unit: '4 pcs (approx 700g)',
    price: 99,
    originalPrice: 129,
    discount: 23,
    category: 'cat_1',
    categoryName: 'Fruits & Vegs',
    stock: 30,
    gradient: 'from-red-100 to-red-200',
    emoji: '🍎',
    description: 'Crunchy, sweet red apples. Perfect for snacking or making apple pies.',
    deliveryTime: '10 mins',
    rating: 4.3,
    reviews: 95,
  },
  {
    _id: 'p_3',
    name: 'Tomatoes',
    unit: '500g',
    price: 29,
    originalPrice: 39,
    discount: 26,
    category: 'cat_1',
    categoryName: 'Fruits & Vegs',
    stock: 60,
    gradient: 'from-red-100 to-orange-100',
    emoji: '🍅',
    description: 'Farm fresh tomatoes, perfect for cooking and salads.',
    deliveryTime: '10 mins',
    rating: 4.2,
    reviews: 73,
  },
  {
    _id: 'p_4',
    name: 'Spinach',
    unit: '250g',
    price: 25,
    originalPrice: 30,
    discount: 17,
    category: 'cat_1',
    categoryName: 'Fruits & Vegs',
    stock: 40,
    gradient: 'from-green-100 to-green-200',
    emoji: '🥬',
    description: 'Fresh, tender spinach leaves. Packed with iron and vitamins.',
    deliveryTime: '10 mins',
    rating: 4.4,
    reviews: 52,
  },
  {
    _id: 'p_5',
    name: 'Onions',
    unit: '1 kg',
    price: 35,
    originalPrice: 45,
    discount: 22,
    category: 'cat_1',
    categoryName: 'Fruits & Vegs',
    stock: 100,
    gradient: 'from-purple-100 to-pink-100',
    emoji: '🧅',
    description: 'Fresh onions, essential for Indian cooking.',
    deliveryTime: '10 mins',
    rating: 4.1,
    reviews: 210,
  },
  // Dairy & Eggs
  {
    _id: 'p_6',
    name: 'Amul Milk',
    unit: '1 L',
    price: 62,
    originalPrice: 62,
    discount: 0,
    category: 'cat_2',
    categoryName: 'Dairy & Eggs',
    stock: 80,
    gradient: 'from-blue-50 to-blue-100',
    emoji: '🥛',
    description: 'Amul Taaza full cream milk, pasteurized and homogenized.',
    deliveryTime: '10 mins',
    rating: 4.7,
    reviews: 342,
  },
  {
    _id: 'p_7',
    name: 'Eggs (White)',
    unit: '6 pcs',
    price: 79,
    originalPrice: 84,
    discount: 6,
    category: 'cat_2',
    categoryName: 'Dairy & Eggs',
    stock: 100,
    gradient: 'from-amber-50 to-amber-100',
    emoji: '🥚',
    description: 'Farm fresh white eggs. High in protein and essential nutrients.',
    deliveryTime: '10 mins',
    rating: 4.6,
    reviews: 287,
  },
  {
    _id: 'p_8',
    name: 'Amul Butter',
    unit: '500g',
    price: 275,
    originalPrice: 290,
    discount: 5,
    category: 'cat_2',
    categoryName: 'Dairy & Eggs',
    stock: 45,
    gradient: 'from-yellow-50 to-yellow-100',
    emoji: '🧈',
    description: 'Amul pasteurized butter, made from fresh cream.',
    deliveryTime: '10 mins',
    rating: 4.8,
    reviews: 189,
  },
  {
    _id: 'p_9',
    name: 'Yogurt (Curd)',
    unit: '400g',
    price: 48,
    originalPrice: 55,
    discount: 13,
    category: 'cat_2',
    categoryName: 'Dairy & Eggs',
    stock: 55,
    gradient: 'from-gray-50 to-gray-100',
    emoji: '🍦',
    description: 'Fresh, creamy curd made from full cream milk.',
    deliveryTime: '10 mins',
    rating: 4.4,
    reviews: 115,
  },
  // Bakery
  {
    _id: 'p_10',
    name: 'Britannia Bread',
    unit: '400g (18 slices)',
    price: 44,
    originalPrice: 50,
    discount: 12,
    category: 'cat_3',
    categoryName: 'Bakery',
    stock: 35,
    gradient: 'from-amber-100 to-orange-100',
    emoji: '🍞',
    description: 'Soft, fresh white bread slices. Perfect for sandwiches and toast.',
    deliveryTime: '10 mins',
    rating: 4.3,
    reviews: 201,
  },
  {
    _id: 'p_11',
    name: 'Croissants',
    unit: '4 pcs',
    price: 99,
    originalPrice: 120,
    discount: 18,
    category: 'cat_3',
    categoryName: 'Bakery',
    stock: 20,
    gradient: 'from-yellow-100 to-amber-100',
    emoji: '🥐',
    description: 'Flaky, buttery croissants baked fresh every morning.',
    deliveryTime: '10 mins',
    rating: 4.6,
    reviews: 67,
  },
  // Beverages
  {
    _id: 'p_12',
    name: 'Coca-Cola',
    unit: '750 ml',
    price: 45,
    originalPrice: 50,
    discount: 10,
    category: 'cat_4',
    categoryName: 'Beverages',
    stock: 120,
    gradient: 'from-red-100 to-red-200',
    emoji: '🥤',
    description: 'Refreshing Coca-Cola in a chilled bottle.',
    deliveryTime: '10 mins',
    rating: 4.5,
    reviews: 456,
  },
  {
    _id: 'p_13',
    name: 'Tropicana Orange',
    unit: '1 L',
    price: 99,
    originalPrice: 115,
    discount: 14,
    category: 'cat_4',
    categoryName: 'Beverages',
    stock: 60,
    gradient: 'from-orange-100 to-yellow-100',
    emoji: '🧃',
    description: '100% pure squeezed orange juice, no added sugar.',
    deliveryTime: '10 mins',
    rating: 4.4,
    reviews: 178,
  },
  {
    _id: 'p_14',
    name: 'Red Bull Energy',
    unit: '250 ml',
    price: 125,
    originalPrice: 135,
    discount: 7,
    category: 'cat_4',
    categoryName: 'Beverages',
    stock: 80,
    gradient: 'from-blue-100 to-indigo-100',
    emoji: '⚡',
    description: 'Red Bull gives you wings! Energy drink with caffeine and B vitamins.',
    deliveryTime: '10 mins',
    rating: 4.3,
    reviews: 234,
  },
  // Snacks
  {
    _id: 'p_15',
    name: "Lay's Classic Salted",
    unit: '90g',
    price: 30,
    originalPrice: 35,
    discount: 14,
    category: 'cat_5',
    categoryName: 'Snacks',
    stock: 90,
    gradient: 'from-yellow-100 to-yellow-200',
    emoji: '🥔',
    description: "Classic Lay's potato chips with just the right amount of salt.",
    deliveryTime: '10 mins',
    rating: 4.4,
    reviews: 512,
  },
  {
    _id: 'p_16',
    name: 'Kurkure Masala Munch',
    unit: '90g',
    price: 20,
    originalPrice: 25,
    discount: 20,
    category: 'cat_5',
    categoryName: 'Snacks',
    stock: 100,
    gradient: 'from-orange-100 to-red-100',
    emoji: '🌶️',
    description: 'Spicy, crunchy Kurkure. A classic Indian snack.',
    deliveryTime: '10 mins',
    rating: 4.5,
    reviews: 389,
  },
  {
    _id: 'p_17',
    name: 'Dark Fantasy Choco Fills',
    unit: '75g',
    price: 40,
    originalPrice: 45,
    discount: 11,
    category: 'cat_5',
    categoryName: 'Snacks',
    stock: 60,
    gradient: 'from-amber-100 to-yellow-100',
    emoji: '🍪',
    description: 'Sunfeast Dark Fantasy cookies filled with chocolate.',
    deliveryTime: '10 mins',
    rating: 4.7,
    reviews: 298,
  },
  // Meat & Fish
  {
    _id: 'p_18',
    name: 'Chicken Breast',
    unit: '500g',
    price: 180,
    originalPrice: 220,
    discount: 18,
    category: 'cat_6',
    categoryName: 'Meat & Fish',
    stock: 25,
    gradient: 'from-orange-50 to-orange-100',
    emoji: '🍗',
    description: 'Fresh boneless chicken breast. High in protein, low in fat.',
    deliveryTime: '10 mins',
    rating: 4.5,
    reviews: 143,
  },
  {
    _id: 'p_19',
    name: 'Rohu Fish',
    unit: '500g (cleaned)',
    price: 220,
    originalPrice: 260,
    discount: 15,
    category: 'cat_6',
    categoryName: 'Meat & Fish',
    stock: 15,
    gradient: 'from-blue-50 to-cyan-100',
    emoji: '🐟',
    description: 'Fresh Rohu fish, cleaned and ready to cook.',
    deliveryTime: '10 mins',
    rating: 4.2,
    reviews: 87,
  },
  // Personal Care
  {
    _id: 'p_20',
    name: 'Dove Soap',
    unit: '3 × 100g',
    price: 119,
    originalPrice: 135,
    discount: 12,
    category: 'cat_7',
    categoryName: 'Personal Care',
    stock: 70,
    gradient: 'from-pink-50 to-pink-100',
    emoji: '🧼',
    description: 'Dove moisturizing beauty bar with 1/4 moisturizing cream.',
    deliveryTime: '10 mins',
    rating: 4.6,
    reviews: 267,
  },
  {
    _id: 'p_21',
    name: 'Head & Shoulders Shampoo',
    unit: '340 ml',
    price: 275,
    originalPrice: 310,
    discount: 11,
    category: 'cat_7',
    categoryName: 'Personal Care',
    stock: 40,
    gradient: 'from-teal-50 to-teal-100',
    emoji: '🧴',
    description: 'Anti-dandruff shampoo for clean, flake-free hair.',
    deliveryTime: '10 mins',
    rating: 4.3,
    reviews: 192,
  },
  // Breakfast
  {
    _id: 'p_22',
    name: "Kellogg's Corn Flakes",
    unit: '875g',
    price: 299,
    originalPrice: 350,
    discount: 15,
    category: 'cat_9',
    categoryName: 'Breakfast',
    stock: 30,
    gradient: 'from-yellow-100 to-amber-50',
    emoji: '🥣',
    description: "Kellogg's original corn flakes. The original and best breakfast cereal.",
    deliveryTime: '10 mins',
    rating: 4.4,
    reviews: 156,
  },
  {
    _id: 'p_23',
    name: 'Quaker Oats',
    unit: '1 kg',
    price: 199,
    originalPrice: 230,
    discount: 13,
    category: 'cat_9',
    categoryName: 'Breakfast',
    stock: 45,
    gradient: 'from-amber-50 to-yellow-50',
    emoji: '🌾',
    description: 'Quaker rolled oats. Whole grain goodness for a healthy start.',
    deliveryTime: '10 mins',
    rating: 4.5,
    reviews: 203,
  },
  // Baby Care
  {
    _id: 'p_24',
    name: "Pampers Diapers",
    unit: 'Size M, 40 count',
    price: 799,
    originalPrice: 950,
    discount: 16,
    category: 'cat_8',
    categoryName: 'Baby Care',
    stock: 20,
    gradient: 'from-blue-50 to-purple-50',
    emoji: '👶',
    description: 'Pampers Active Baby Dry diapers, up to 12 hours protection.',
    deliveryTime: '10 mins',
    rating: 4.7,
    reviews: 312,
  },
]

export const BANNERS = [
  {
    id: 1,
    title: 'Groceries in 10 Minutes',
    subtitle: 'Get fresh fruits, vegetables & more delivered at your doorstep',
    cta: 'Order Now',
    gradient: 'from-primary to-green-400',
    emoji: '⚡',
    tag: 'FREE DELIVERY on first order',
  },
  {
    id: 2,
    title: 'Fresh Fruits & Veggies',
    subtitle: 'Farm-fresh produce delivered straight to your home',
    cta: 'Shop Now',
    gradient: 'from-orange-400 to-yellow-400',
    emoji: '🥦',
    tag: 'Up to 30% OFF',
  },
  {
    id: 3,
    title: 'Dairy Essentials',
    subtitle: 'Milk, Eggs, Butter, Cheese & more at best prices',
    cta: 'Explore',
    gradient: 'from-blue-500 to-cyan-400',
    emoji: '🥛',
    tag: 'New Arrivals',
  },
]

export const MOCK_ORDERS = [
  {
    _id: 'ORD_001',
    orderNumber: 'BLK2024001',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'delivered',
    items: [
      { product: PRODUCTS[0], quantity: 2 },
      { product: PRODUCTS[5], quantity: 1 },
      { product: PRODUCTS[6], quantity: 2 },
    ],
    subtotal: 261,
    deliveryFee: 0,
    handlingFee: 5,
    total: 266,
    address: {
      label: 'Home',
      line1: '42 Green Park Extension',
      city: 'New Delhi',
      pincode: '110016',
    },
    paymentMethod: 'Online',
    timeline: [
      { status: 'placed', label: 'Order Placed', time: '10:30 AM', done: true },
      { status: 'confirmed', label: 'Order Confirmed', time: '10:31 AM', done: true },
      { status: 'preparing', label: 'Preparing Order', time: '10:33 AM', done: true },
      { status: 'picked', label: 'Picked Up', time: '10:38 AM', done: true },
      { status: 'delivered', label: 'Delivered', time: '10:42 AM', done: true },
    ],
  },
  {
    _id: 'ORD_002',
    orderNumber: 'BLK2024002',
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    status: 'preparing',
    items: [
      { product: PRODUCTS[14], quantity: 1 },
      { product: PRODUCTS[9], quantity: 1 },
      { product: PRODUCTS[11], quantity: 2 },
    ],
    subtotal: 164,
    deliveryFee: 0,
    handlingFee: 5,
    total: 169,
    address: {
      label: 'Home',
      line1: '42 Green Park Extension',
      city: 'New Delhi',
      pincode: '110016',
    },
    paymentMethod: 'COD',
    timeline: [
      { status: 'placed', label: 'Order Placed', time: '2:00 PM', done: true },
      { status: 'confirmed', label: 'Order Confirmed', time: '2:01 PM', done: true },
      { status: 'preparing', label: 'Preparing Order', time: '2:03 PM', done: true },
      { status: 'picked', label: 'Picked Up', time: null, done: false },
      { status: 'delivered', label: 'Delivered', time: null, done: false },
    ],
  },
  {
    _id: 'ORD_003',
    orderNumber: 'BLK2024003',
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'delivered',
    items: [
      { product: PRODUCTS[17], quantity: 1 },
      { product: PRODUCTS[7], quantity: 1 },
      { product: PRODUCTS[12], quantity: 1 },
    ],
    subtotal: 404,
    deliveryFee: 0,
    handlingFee: 5,
    total: 409,
    address: {
      label: 'Work',
      line1: 'Plot 5B, Sector 18',
      city: 'Noida',
      pincode: '201301',
    },
    paymentMethod: 'Online',
    timeline: [
      { status: 'placed', label: 'Order Placed', time: '11:15 AM', done: true },
      { status: 'confirmed', label: 'Order Confirmed', time: '11:16 AM', done: true },
      { status: 'preparing', label: 'Preparing Order', time: '11:18 AM', done: true },
      { status: 'picked', label: 'Picked Up', time: '11:23 AM', done: true },
      { status: 'delivered', label: 'Delivered', time: '11:28 AM', done: true },
    ],
  },
  {
    _id: 'ORD_004',
    orderNumber: 'BLK2024004',
    createdAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    status: 'out_for_delivery',
    estimatedDelivery: new Date(Date.now() + 10 * 60 * 1000).toISOString(),
    driver: { name: 'Rajesh Kumar', phone: '+91 98765 43210', vehicle: 'Bike - DL 5S AB 1234' },
    items: [
      { product: PRODUCTS[0], quantity: 2 },
      { product: PRODUCTS[4], quantity: 1 },
    ],
    subtotal: 213,
    deliveryFee: 0,
    handlingFee: 5,
    total: 218,
    address: {
      label: 'Home',
      line1: '42 Green Park Extension',
      city: 'New Delhi',
      pincode: '110016',
    },
    paymentMethod: 'COD',
    timeline: [
      { status: 'placed', label: 'Order Placed', time: '3:00 PM', done: true },
      { status: 'confirmed', label: 'Order Confirmed', time: '3:01 PM', done: true },
      { status: 'preparing', label: 'Preparing Order', time: '3:03 PM', done: true },
      { status: 'picked', label: 'Picked Up', time: '3:09 PM', done: true },
      { status: 'delivered', label: 'Delivered', time: null, done: false },
    ],
  },
]
